@startuml Camera2

hide footbox
skinparam {
    ' defaultFontName Abyssinica SIL
    Shadowing false
    backgroundColor white
    NoteFontColor #Black
    NoteFontSize 16
    NoteTextAlignment left
    NoteBackgroundColor WhiteSmoke
    NoteColor transparent
    NoteBorderThickness 0
    NoteBorderColor transparent
    NoteBorderThickness 0
    NoteShadowing false
    ParticipantPadding 0
    BoxPadding 20
    dpi 96
    ClassBackgroundColor transparent
    ClassHeaderBackgroundColor lightgreen
    ClassStereotypeFontColor transparent
    SequenceBoxBordercolor WhiteSmoke
    SequenceBoxFontSize 24
    SequenceBoxFontColor Black
    SequenceBoxBackgroundColor WhiteSmoke
    SequenceLifeLineBackgroundColor WhiteSmoke
    SequenceMessageAlignment center
    SequenceGroupHeaderFontColor White
    SequenceGroupHeaderFontSize 20
    SequenceGroupBackgroundColor DarkOliveGreen
    SequenceGroupBodyBackgroundColor transparent
    SequenceGroupBorderThickness 4
    SequenceGroupBorderColor DarkOliveGreen
    ' transparent
    sequence {
        ParticipantBackgroundColor WhiteSmoke
        ParticipantBorderColor Gray
        ParticipantFontStyle Bold
        ParticipantFontSize 12
        ParticipantPadding 0

        LifeLineBorderColor DimGray
        ArrowColor Black
        ArrowThickness 0.8
        ColorArrowSeparationSpace 30
    }
}

->CameraCommandExecutor:run()
CameraCommandExecutor->PictureTakerCommand:run()
PictureTakerCommand->FlashBasedPhotoCommand:run()
FlashBasedPhotoCommand->ConvergedImageCaptureCommand:run()
ConvergedImageCaptureCommand->ConvergedImageCaptureCommand:captureBurst()
ConvergedImageCaptureCommand->SessionImpl:submitRequest()
SessionImpl->FrameServerImpl:submitRequest()
FrameServerImpl->TagDispatchCaptureSession:submitRequest()
TagDispatchCaptureSession->AndroidCameraCaptureSessionProxy:captureBurst()
AndroidCameraCaptureSessionProxy->CameraCaptureSessionImpl: